# Generated by Django 3.2 on 2021-12-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_va_ten', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('profile_image', models.ImageField(default='customers_profile/default.jpg', upload_to='customers_profile')),
                ('mat_khau', models.CharField(max_length=100)),
                ('dien_thoai', models.CharField(max_length=20)),
                ('dia_chi', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
